---
"*.{js,ts}":
  - bunx @biomejs/biome lint --write src
  - bunx @biomejs/biome format --write src
  - bunx @biomejs/biome check --write src
"*.{css,scss,sass}":
  - bunx @biomejs/biome lint --write src
  - bunx @biomejs/biome format --write src
  - bunx @biomejs/biome check --write src