name: Deploy to Release
on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/' + ${{ github.event.repository.default_branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        if: ${{ github.event.head.user.login == 'act' }}
        run: |
          apt-get update
          apt-get install -y unzip zip jq
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install and Build
        run: |
          bun install --frozen-lockfile --ignore-scripts
          bun run build
      - name: Get Version
        id: current_version
        run: |
          echo "version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
